name: "Computer Vision Lab"
university: "Sungkyunkwan University"
address: "Computer Vision Laboratory (85745), Research & Business Center, Sungkyunkwan University. 300 CheonCheon-dong, Jangan-gu, Suwon, Gyeonggi-do, 440-746. South Korea."
tel: "+82-31-290-7227"
fax: "+82-31-290-7947"
email: "junehoyr@skku.edu"
